# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: tour
    weight: 10
  - name: 深度学习
    url: deeplearning
    weight: 20
  - name: 大模型
    url: bigM
    weight: 30
  - name: E-cargo
    url: ecargo
    weight: 40
  - name: LDM
    url: ldm
    weight: 50
  - name: People
    url: people
    weight: 60
  - name: Contact
    url: contact
    weight: 70
